### ISSUE TITLE
Occasionally failing tests in pika-algorithms

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika-algorithms#24]
This issue is meant to collect the names of failing tests together with links to the failures for investigation. This is a long-running issue and will likely not be closed by one or only a few PRs.

**Comment by barracuda156** [comment]
Most of headers tests fail simply due to wrong paths:
```
In file included from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_pika-algorithms/pika-algorithms/work/build/tests/pika/parallel/algorithms/reduce_by_key.cpp:1:
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_pika-algorithms/pika-algorithms/work/pika-algorithms-0.1.4/include/pika/parallel/algorithms/reduce_by_key.hpp:12:10: fatal error: pika/execution/executors/execution.hpp: No such file or directory
   12 | #include <pika/execution/executors/execution.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [tests/CMakeFiles/tests_headers_algorithms_pika_parallel_algorithms_reduce_by_key_hpp.dir/pika/parallel/algorithms/reduce_by_key.cpp.o] Error 1
make[2]: *** [tests/CMakeFiles/tests_headers_algorithms_pika_parallel_algorithms_reduce_by_key_hpp.dir/all] Error 2
make[1]: *** [tests/CMakeFiles/tests_headers_algorithms_pika_parallel_algorithms_reduce_by_key_hpp.dir/rule] Error 2
make: *** [tests_headers_algorithms_pika_parallel_algorithms_reduce_by_key_hpp] Error 2
```
There is nothing like this header in the pointed location. There is `pika/execution.hpp`. Etc.

**Comment by msimberg** [comment]
Hi @barracuda156. I'm sorry to say that this is expected, as with pika 0.21.0 we've stopped supporting pika-algorithms, and we have no plans to continue supporting pika-algorithms at least in its current form. Things should still work with pika 0.20.0. Long term the plan is to work on integrating parallel algorithms with e.g. `stdexec` (which has some work on one or a few parallel algorithms, but it's not very comprehensive). If you're looking to use parallel algorithms with a tasking runtime _today_ I recommend you stick to HPX, from which pika was forked.

I'll try to make this visible somewhere in the readme.
